version: "3"
services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/frontend-demo/node_modules
      - .:/usr/frontend-demo
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/frontend-demo/node_modules
      - .:/usr/frontend-demo
    command: ["yarn", "test"]
